name: desafio-um
on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Imagem Docker a ser utilizada'
        required: true
        type: string

jobs:
  desafio-um:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar imagem Docker
        run: docker pull ${{ inputs.docker_image }}

      - name: mostrar imagens no runner
        run: docker images

      - name: Informar imagem sendo utilizada
        run: echo "Executando na imagem ${{ inputs.docker_image }}"

      - name: Executar Container
        run: docker run -rm ${{ inputs.docker_image }}






















        