name: desafio-um
on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Imagem Docker a ser utilizada'
        required: true
        type: string

jobs:
  desafio-um:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar imagem Docker
        run: docker pull ${{ inputs.docker_image }}

      - name: mostrar imagens no runner
        run: docker images

      - name: Analisar imagem com Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ inputs.docker_image }}
          summary: true
        
         
